<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Configuration.fs" />
    <Compile Include="Persistence.fs" />
    <Compile Include="TerminalGraphics.fs" />
    <Compile Include="OutputRendering.fs" />
    <Compile Include="SyntaxHighlighting.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lfsi.Core\Lfsi.Core.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Consolonia" Version="11.3.9" />
    <PackageReference Update="FSharp.Core" Version="10.1.201" />
    <PackageReference Include="FSharp.Compiler.Service" Version="43.12.201" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
  </ItemGroup>

</Project>
